#!/bin/sh

# Define some colours.
aqua="#92b7c0"
black="#0f1116"
blue="#89a0c3"
green="#b6bd88"
purple="#9e94c3"
red="#d47d7b"
white="#c6c8d0"
yellow="#d9a67e"

lock() {
    i3lock \
    --insidever-color=$black \
    --ringver-color=$yellow \
    --insidewrong-color=$black \
    --ringwrong-color=$red \
    --inside-color=$black \
    --ring-color=$black \
    --line-color=$black \
    --separator-color=$blue \
    --verif-color=$yellow \
    --wrong-color=$red \
    --time-color=$white \
    --date-color=$white \
    --layout-color=$aqua \
    --keyhl-color=$white \
    --bshl-color=$white \
    --blur 8 \
    --verif-text="Checking ..." \
    --wrong-text="Wrong." \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%A, %m %Y"
}

lock
