#!/bin/bash
# Bash Script to move newly downloaded pdf into a temp directory and open it in zathura.

echo "Starting pdfsort ... "

echo "Check for previous instances and killing them ..."

PIDS=`ps cax | grep inotifywait | grep -o '^[ ]*[0-9]*'` 

if [ ! -z "$PIDS" ]; then
    for PID in $PIDS; do
        kill $PID
    done
fi

# Set some path variables
path=$HOME/Downloads
tmp=/tmp/pdfDirectory

# Move downloaded pdf and open it in zathura then send a notification.
openzathura(){

    mv "$path/$file" "$tmp/$file"
    # As long as this is zathura and not Chrome. It won't keep looping in Chrome.
    zathura "$tmp/$file" &> /dev/null &
    notify-send -t 5000 "$file opened in Zathura"
    prevfile=$file
}

inotifywait -m --format "%f" -e moved_to "$path" | while read file;do

    # Remove the same file that exists in the tmp directory before processing the new one.
    if [[ $prevfile != $file ]];then

        if [[ $file == *.pdf ]];then
            
            if [[ ! -d "$tmp" ]];then mkdir "$tmp";fi

            openzathura
        fi
    else

        # Remove the Old File and Open the Newly downloaded file
        rm "$tmp/$file"
        openzathura
    fi
done
