#!/bin/sh

# Define some colours.
aqua="#8EC07C"
black="#282828"
blue="#83A598"
green="#B8BB26"
purple="#D3869B"
red="#FB4934"
white="#EBDDB2"
yellow="#FABD2F"

lock() {
    i3lock \
    --insidever-color=$black \
    --ringver-color=$yellow \
    --insidewrong-color=$black \
    --ringwrong-color=$red \
    --inside-color=$black \
    --ring-color=$black \
    --line-color=$black \
    --separator-color=$blue \
    --verif-color=$yellow \
    --wrong-color=$red \
    --time-color=$white \
    --date-color=$white \
    --layout-color=$aqua \
    --keyhl-color=$white \
    --bshl-color=$white \
    --blur 8 \
    --verif-text="Checking ..." \
    --wrong-text="Wrong." \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%A, %m %Y" \
    --time-font "Scientifica" \
    --date-font "Scientifica"
}

lock
