#!/bin/sh

# Define some colours.
aqua="#92b7c0"
black="#0f1116"
blue="#89a0c3"
green="#b6bd88"
purple="#9e94c3"
red="#d47d7b"
white="#c6c8d0"
yellow="#d9a67e"

lock() {
    i3lock \
    --insidevercolor=$black \
    --ringvercolor=$yellow \
    --insidewrongcolor=$black \
    --ringwrongcolor=$red \
    --insidecolor=$black \
    --ringcolor=$black \
    --linecolor=$black \
    --separatorcolor=$blue \
    --verifcolor=$yellow \
    --wrongcolor=$red \
    --timecolor=$white \
    --datecolor=$white \
    --layoutcolor=$aqua \
    --keyhlcolor=$white \
    --bshlcolor=$white \
    --blur 8 \
    --veriftext="Checking ..." \
    --wrongtext="Wrong." \
    --clock \
    --indicator \
    --timestr="%H:%M:%S" \
    --datestr="%A, %m %Y"
}

lock
